version: "3.3"
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: dcamp/jenkins-test:latest
    ports:
      - "80:8080"
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
