version: "3.3"
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: dcamp/jenkins-test:latest
    ports:
      - "80:8080"
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
  sut:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - jenkins
    command: ["./wait-for-it.sh", "jenkins:80", "--timeout=240", "--", "./run_tests.sh"]
